name: codebuilddeploy-web

networks:
  development:
    name: codebuilddeploy
    driver: bridge

services:
  codebuilddeploy-web:
    image: codebuilddeploy.azurecr.io/codebuilddeploy-web:latest
    build:
      context: .
      dockerfile: ./src/CodeBuildDeploy.Web/Dockerfile
      target: final
      args:
        FEED_ACCESSTOKEN: $FEED_ACCESSTOKEN
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+:5001
      ASPNETCORE_Kestrel__Certificates__Default__Password: $CERT_PASSWORD
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/code-build-deploy.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    ports:
      - 5001:5001
    networks:
      - development
    container_name: codebuilddeploy-web
    hostname: codebuilddeploy-web